// Generated by CoffeeScript 1.10.0
(function() {
  var app, crypto, express, multer, path, storage;

  express = require('express');

  multer = require('multer');

  path = require('path');

  crypto = require('crypto');

  app = new express();

  storage = multer.diskStorage({
    destination: './uploads',
    filename: function(req, file, cb) {
      return crypto.pseudoRandomBytes(16, function(err, raw) {
        if (err) {
          return cb(err);
        }
        return cb(null, "" + (raw.toString('hex')) + (path.extname(file.originalname)));
      });
    }
  });

  app.post('/', multer({
    storage: storage
  }).single('upload'), function(req, res) {
    console.log(req.file);
    console.log(req.body);
    return res.status(204).end();
  });

  app.listen(3000, console.log("Listening on port 3000"));

}).call(this);
